version: '3.8'
services:
  nestcorebase:
    build: 
      context: .
      args:
        NODE_ENV: 'development'
    container_name: nestcorebase
    hostname: nestcorebase
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: always

