name: Linter
on:

  workflow_dispatch:
  pull_request:
    branches: 
    - main

jobs:
  linter:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile
          
      - name: Linter
        run: yarn lint
